# Generated by Django 3.2 on 2021-04-26 06:57

from django.db import migrations, models
import portfolio_settings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteTitle', models.CharField(max_length=150)),
                ('logo_image', models.ImageField(null=True, upload_to=portfolio_settings.models.upload_image_path)),
                ('address', models.CharField(max_length=400)),
                ('mobile', models.CharField(max_length=50)),
                ('twitter', models.URLField(max_length=50)),
                ('instagram', models.URLField(max_length=50)),
                ('linkedin', models.URLField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('clients', models.IntegerField()),
                ('projects', models.IntegerField()),
                ('hours_of_supports', models.IntegerField()),
                ('awards', models.IntegerField()),
            ],
        ),
    ]
