# Generated by Django 3.2 on 2021-04-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_settings', '0004_sitesetting_fav_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='awards',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='happy_client',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hours_of_support',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='projects_count',
            field=models.IntegerField(null=True),
        ),
    ]
