# Generated by Django 3.2 on 2023-09-08 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_settings', '0005_auto_20210430_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesetting',
            old_name='twitter',
            new_name='github',
        ),
    ]
