# Generated by Django 3.2 on 2023-09-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_settings', '0007_myskills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=100)),
                ('class_icon', models.CharField(max_length=50)),
            ],
        ),
    ]
