services:

  app:
    build:
      context: .
    container_name: 'django-app'
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000

    volumes:
      - ./volumes/app:/usr/src/app

    working_dir: /usr/src/app
    
    depends_on:
      - "database"
    
    restart: always
    
    environment:
      - ALLOWED_HOSTS=*
      - DEBUG=False
      - DATABASE-NAME=postgres
      - DATABASE-USER=postgres
      - DATABASE-PASSWORD=postgres
      - DATABASE-HOST=database
      - DATABASE-PORT=5432


  database:
    container_name: database
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    expose:
      - 5432
    restart: always


  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '5000:80'
      - '25:25'
      - '143:143'
    volumes:
      - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev

volumes:
  smtp4dev-data: