# Generated by Django 4.2.18 on 2025-02-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default='description', max_length=300)),
                ('image', models.ImageField(upload_to='photo')),
                ('birth_date', models.DateField()),
                ('website', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('degree', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('freelance', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='MyInformations',
            new_name='Website',
        ),
        migrations.RenameField(
            model_name='socialmedias',
            old_name='site_setting',
            new_name='website',
        ),
    ]
