# Generated by Django 4.2.18 on 2025-02-01 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_myinformation_skills_rename_myinformations_website_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myinformation',
            name='age',
        ),
    ]
