# Generated by Django 4.2.18 on 2025-02-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_myinformation_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myinformation',
            name='description',
            field=models.TextField(default='description', max_length=500),
        ),
    ]
