# Generated by Django 4.2.18 on 2025-02-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_myinformation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myinformation',
            name='description',
            field=models.TextField(default='description'),
        ),
    ]
