# Generated by Django 4.2.18 on 2025-02-01 12:52

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_myinformation_created_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedias',
            old_name='website',
            new_name='socials',
        ),
        migrations.CreateModel(
            name='InterestedIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None)),
                ('icon', models.CharField(max_length=50)),
                ('interested', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interested', to='website.myinformation')),
            ],
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('value', models.IntegerField(null=True)),
                ('icon', models.CharField(max_length=50)),
                ('counter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter', to='website.myinformation')),
            ],
        ),
    ]
