# Generated by Django 4.2.18 on 2025-02-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['-created_date']},
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='created',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='contactus',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
