# Generated by Django 4.2.18 on 2025-02-05 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_contactus_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='description',
            new_name='message',
        ),
    ]
