# Generated by Django 4.2.18 on 2025-02-12 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_rename_description_contactus_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='socialmedias',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterField(
            model_name='skills',
            name='value',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
