# Generated by Django 4.2.18 on 2025-02-12 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_skills_options_alter_socialmedias_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedias',
            options={},
        ),
    ]
