# Generated by Django 4.2.18 on 2025-02-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('till_date', models.DateField(blank=True, null=True)),
                ('university', models.CharField(blank=True, max_length=255, null=True)),
                ('university_location', models.CharField(max_length=255)),
                ('description', models.TextField(default='description', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('till_date', models.DateField(blank=True, null=True)),
                ('company', models.CharField(max_length=255)),
                ('company_location', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(default='description', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default='description', max_length=300)),
                ('short_description', models.TextField(default='description', max_length=300)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
