# Generated by Django 4.2.18 on 2025-02-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_summary_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='university',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='university_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
