# Generated by Django 4.2.18 on 2025-02-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_education_university_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='university',
            field=models.CharField(default='university', max_length=255),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(default='company', max_length=255),
        ),
    ]
