# Generated by Django 4.2.18 on 2025-02-01 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_education_university_alter_experience_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-from_date']},
        ),
    ]
