# Generated by Django 4.2.18 on 2025-02-01 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_alter_experience_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-from_date']},
        ),
    ]
