# Generated by Django 4.2.18 on 2025-02-01 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_alter_experience_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='address',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='email',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='phone',
        ),
    ]
