# Generated by Django 4.2.18 on 2025-02-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_remove_summary_address_remove_summary_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(default='description'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(default='description'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='description',
            field=models.TextField(default='description'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='short_description',
            field=models.TextField(default='short description', max_length=500),
        ),
    ]
