# Generated by Django 4.2.18 on 2025-02-02 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=150)),
                ('description', models.TextField(default='description')),
                ('client', models.CharField(default='user', max_length=150)),
                ('website', models.CharField(max_length=150, null=True)),
                ('project_date', models.DateField(null=True)),
                ('thumbnail', models.ImageField(upload_to='resume/thumbnail')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='resume/gallery')),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='portfolio.resume')),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='categories',
            field=models.ManyToManyField(to='portfolio.resumecategory'),
        ),
    ]
