# Generated by Django 3.2 on 2023-09-08 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=150)),
                ('description', models.TextField(default='description', max_length=300)),
                ('client', models.CharField(default='user', max_length=150)),
                ('website', models.CharField(max_length=150, null=True)),
                ('Date', models.DateField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='resume')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='resume-gallery')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='portfolio_resume.resume')),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='categories',
            field=models.ManyToManyField(blank=True, to='portfolio_resume.ResumeCategory'),
        ),
    ]
