# Generated by Django 3.2 on 2021-04-28 11:34

from django.db import migrations, models
import django.db.models.deletion
import portfolio_resume.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('client', models.CharField(max_length=150)),
                ('website', models.CharField(max_length=150)),
                ('Date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=portfolio_resume.models.upload_image_path)),
                ('categories', models.ManyToManyField(blank=True, to='portfolio_resume.ResumeCategory')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to=portfolio_resume.models.upload_gallery_image_path)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_resume.resume')),
            ],
        ),
        migrations.RemoveField(
            model_name='productsgallery',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductsGallery',
        ),
    ]
