# Generated by Django 5.1.5 on 2025-01-29 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumegallery',
            name='image',
            field=models.ImageField(upload_to='resume/gallery'),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('till_date', models.DateField(blank=True, null=True)),
                ('university', models.CharField(max_length=255)),
                ('description', models.TextField(default='description', max_length=300)),
                ('education', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='portfolio_resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('till_date', models.DateField(blank=True, null=True)),
                ('company', models.CharField(max_length=255)),
                ('description', models.TextField(default='description', max_length=300)),
                ('exprience', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exprience', to='portfolio_resume.resume')),
            ],
        ),
    ]
