# Generated by Django 3.2 on 2021-04-28 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_resume', '0003_resume_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='name',
        ),
    ]
