# Generated by Django 3.2 on 2021-04-28 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_resume', '0004_remove_resume_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='categories',
            new_name='categoriess',
        ),
    ]
