# Generated by Django 3.2 on 2021-04-28 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_resume', '0005_rename_categories_resume_categoriess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='categoriess',
            new_name='categories',
        ),
    ]
