# Generated by Django 3.2 on 2021-04-28 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_resume', '0007_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='client',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='description',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='image',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='website',
        ),
    ]
