# Generated by Django 3.2 on 2021-04-28 17:05

from django.db import migrations, models
import portfolio_resume.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_resume', '0008_auto_20210428_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='categories',
            field=models.ManyToManyField(blank=True, to='portfolio_resume.ResumeCategory'),
        ),
        migrations.AddField(
            model_name='resume',
            name='client',
            field=models.CharField(default='user', max_length=150),
        ),
        migrations.AddField(
            model_name='resume',
            name='description',
            field=models.TextField(default='description', max_length=300),
        ),
        migrations.AddField(
            model_name='resume',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio_resume.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='resume',
            name='website',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(default='title', max_length=150),
        ),
    ]
