# Generated by Django 3.2 on 2021-04-28 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_resume', '0009_auto_20210428_2135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
