# Generated by Django 3.2 on 2023-09-08 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_resume', '0012_alter_services_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.AlterField(
            model_name='resumegallery',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='portfolio_resume.resume'),
        ),
    ]
